version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/proxy_params:/etc/nginx/proxy_params:ro
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - lake
      - proxy

  lake:
    build:
      context: ./lake
      dockerfile: Dockerfile
    container_name: lake
    ports:
      - "8080:80"
    networks:
      - app-network

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy
    ports:
      - "8081:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge